DB:
  Mysql:
    Enabled: true
    Host: "localhost"
    Port: 3306
    Database: "oneinthechamber"
    Username: "root"
    Password: ""
  Mongodb:
    Enabled: false
    Hostname: "mongodb+srv://Lacratus:Bootcamp1@cluster0.utukr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
    Database: "OneInTheChamber"

Message:
  AddLocation: "&8[&bOITC&8] &f Locatie toegevoegd."
  JoinGame : "&8[&bOITC&8] &f Game joined."
  GameStarted: "&8[&bOITC&8] &f The game is already being played."
  InGame: "&8[&bOITC&8] &f U are already in a game."
  NoPermission: "&8[&bOITC&8] &fJe hebt geen permissie tot deze command."
  NoLocationAllocated: "&8[&bOITC&8] &f Er zijn geen locaties aangeduid."
  StartGame: "&8[&bOITC&8] &f Game is starting."
  ArenaAlreadyExists: "&8[&bOITC&8] &f Arena already exists."
  ArenaNotExist: "&8[&bOITC&8] &f Arena doesn't exist."
  SpawnLocationNotSet: "&8[&bOITC&8] &f Arena spawnlocation is not set."
  ArenaCreated: "&8[&bOITC&8] &f Arena successfully created"
  ArenaDeleted: "&8[&bOITC&8] &f Arena successfully deleted"
Game:
  RegenerateArrowSeconds: 10
  StandardDurationGame: 10


